public class Subwoofer extends Sounds{
    public Subwoofer() {
        description = "A subwoofer (or sub) is a loudspeaker designed" +
                " to reproduce low-pitched audio frequencies known as " +
                "bass and sub-bass, lower in frequency than those which" +
                " can be (optimally) generated by a woofer.";
    }
}
